name: portfolio
description: A showcase of my journey as a software engineering student
version: 1.0.1+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  animate_do: ^2.0.0
  bloc: ^8.0.1
  fab_circular_menu: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  url_launcher: ^6.0.17

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_native_splash: ^1.3.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
